config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  resources :tasks do
  # resources :tasksの中身
  # # CRUD
  # get 'tasks/:id', to: 'tasks#show'
  # post 'tasks', to: 'tasks#create'
  # put 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'
  # # 一覧ページ(index)の追加 ← 詳細ページ(show)
  # get 'tasks', to: 'tasks#index'
  # # 新規作成用のフォームページ(new)
  # get 'tasks/new', to: 'tasks#new'
  # # 編集用のフォームページ(edit)
  # get 'tasks/:id/edit', to: 'tasks#edit'
  collection do
      get 'calendar', to: 'tasks#calendar'
      get 'custom', to: 'tasks#custom'
      get 'custom_alert', to: 'tasks#custom_alert'
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'forms', to: 'forms#create'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:new,:create,:edit,:update]
  
  resources :stories
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, length: { maximum: 555 }
  validates :card_color, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  before_action :require_user_logged_in
  before_action :correct_user, only:[:show,:edit,:update,:destroy]
  before_action :set_story, only:[:show,:edit,:update,:destroy]
  before_action :set_storylist, only:[:index,:show,:new,:create,:edit,:update]
  
  def index
  end

  def show
  end

  def new
    @story = current_user.stories.build
  end

  def create
    @story = current_user.stories.build(story_params)
    if @story.save
      flash[:success] = 'storyの作成に成功しました'
      redirect_to stories_path
    else
      flash.now[:danger] = 'storyの作成に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)
      flash[:success] = 'storyは正常に更新されました'
      redirect_to stories_path
    else
      flash.now[:danger] = 'storyは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @story.destroy
    flash[:success] = 'Taskは正常に削除されました'
    redirect_to stories_path
  end
  
  private
  
  def set_story
    @story = current_user.stories.find(params[:id])
  end
  
  def set_storylist
    @stories = current_user.stories.order(id: :desc).page(params[:page])
  end
  
  def story_params
    params.require(:story).permit(:title,:status,:content,:card_color,:favorite_score)
    # 必要なパラメータを把握し、送信データを精査する。
    # 本来ならparams.require(:task).permit(:title,:content,:start_date,:end_date)まで書く予定だったが、
    # doneやnot doneなどのボタンが上手く作動せず、require(:task)を抜くことで上手く作動したので、require(:task)を抜いた。
    # require(:task)は、Taskモデルのフォームから得られるデータに関するものであると明示するものであるため、
    # doneやnot doneなどのボタンが上手く作動しない。
  end
  
  def correct_user
    @story = current_user.stories.find_by(id: params[:id])
    unless @story
      redirect_to root_url
    end
  end
end

app/views/stories/_favorite_stories.html.erb
<% [3,2,1].each do |favorite_score_number| %>

  <% stories.each do |story| %>

    <% if story.favorite_score.to_i == favorite_score_number %>
    
      <%= render 'stories/story_card', story: story %>
      
    <% end %>

  <% end %>
  
<% end %>

app/views/stories/_form.html.erb
<div style="margin:10px 5px 10px 5px">
  <font size='2' color='#999999'>タイトル・カードの色は入力必須</font><br>
  <font size='2' color='#999999'>お気に入り評価値は0~3から選択可能</font>
</div>

<%= form_with(model: @story, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title, 'タイトル(30字以下)' %>
      <%= f.text_field :title ,class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content, '内容&関連情報' %>
      <%= f.text_area :content, rows: 5 ,class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.radio_button :favorite_score, 0 %>
      <%= f.label :favorite_score, "☆0", {value: 0, style: "display: inline-block;"} %>
      <%= f.radio_button :favorite_score, 1 %>
      <%= f.label :favorite_score, "☆1", {value: 1, style: "display: inline-block;"} %>
      <%= f.radio_button :favorite_score, 2 %>
      <%= f.label :favorite_score, "☆2", {value: 2, style: "display: inline-block;"} %>
      <%= f.radio_button :favorite_score, 3 %>
      <%= f.label :favorite_score, "☆3", {value: 3, style: "display: inline-block;"} %>
    </div>
    <div class="field" style="margin:0px 0px 25px 0px">
      <%= f.label :card_color, 'カードの色' %>
      <%= f.select :card_color, {'赤': 'danger', '黄': 'warning','緑': 'success', '青': 'primary', '黒': 'dark'}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
    </div>
    
    <%= f.hidden_field :status, :value => "unread" %>
    <%= f.submit 'Add', class: 'btn btn-primary btn-block'%>
<% end %>



  

app/views/stories/_stories.html.erb
<% stories.each do |story| %>

  <%= render 'stories/story_card', story: story %>

<% end %>

app/views/stories/_stories_navbar.html.erb
<!--ナビバー-->
<ul class="nav nav-tabs nav-justified mb-3">
<!--All……下記のナビバーをクリックすることにより、全てのストーリーを表示する-->
  <li class="nav-item"><a href="#all_stories" class="nav-link" data-toggle="tab">All Stories</a></li>
  <!--今日-->
  <li class="nav-item"><a href="#unread_stories" class="nav-link active" data-toggle="tab">Unread Stories</a></li>
  <!--明日-->
  <li class="nav-item"><a href="#favorite_stories" class="nav-link" data-toggle="tab">Favorite Stories</a></li>
</ul>

<!--内容-->
<div class="tab-content">
  <div id="all_stories" class="tab-pane">
    <div class ="text-center" style="margin:25px 10px 25px 10px">
      <font size='2' color='#999999'>全ての作品</font>
    </div>
    <%= render 'stories/stories', stories: @stories %>
  </div>
  <div id="unread_stories" class="tab-pane active">
    <div class ="text-center" style="margin:25px 10px 25px 10px">
      <font size='2' color='#999999'>全ての未鑑賞の作品</font>
    </div>
    <%= render 'stories/unread_stories', stories: @stories %>
  </div>
  <div id="favorite_stories" class="tab-pane">
    <div class ="text-center" style="margin:25px 10px 25px 10px">
      <font size='2' color='#999999'>全てのお気に入り作品</font><br>
      <font size='2' color='#999999'>お気に入り評価値の高い順に並んでいます</font>
    </div>
    <%= render 'stories/favorite_stories', stories: @stories %>
  </div>
</div>

app/views/stories/_story_card.html.erb
<% if current_page?(stories_path) %>
<!--story一覧ページでのカードの表記-->

  <div class="card linkbox border-<%= story.card_color %>" style="margin: 25px ; padding: 15px">
    <div class="row">
      <div class="col-9">
        <table>
          <tr>
            <td align="left"><%= story.title %></td>
            <td align="right">
              <% if story.favorite_score == '1' %>
                ☆１
              <% elsif story.favorite_score == '2' %>
                ☆２
              <% elsif story.favorite_score == '3' %>
                ☆３
              <% else %>
                ☆０
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <a href="/stories/<%= story.id %>"></a>
      <div class="col-1">
        <!--鑑賞済or未鑑賞-->
        <% if story.status == 'read' %>
          <%= form_with(model: story, local: true) do |f| %>
            <%= f.hidden_field :status, :value => "unread" %>
            <%= f.submit '鑑賞済', class: 'btn btn-success btn-sm'%>
          <% end %>
        <% else %>
          <%= form_with(model: story, local: true) do |f| %>
            <%= f.hidden_field :status, :value => "read" %>
            <%= f.submit '未鑑賞', class: 'btn btn-danger btn-sm'%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  
<% else %>
<!--それ以外のページでのカードの表記-->


  <div class="card linkbox border-<%= story.card_color %>" style="margin: 25px ; padding: 15px">
    <a href="/stories/<%= story.id %>"></a>
      <table>
        <tr>
          <td align="left"><%= story.title %></td>
          <td align="right">
            <% if story.favorite_score == '1' %>
              ☆１
            <% elsif story.favorite_score == '2' %>
              ☆２
            <% elsif story.favorite_score == '3' %>
              ☆３
            <% else %>
              ☆０
            <% end %>
          </td>
        </tr>
      </table>
  </div>
  
  
<% end %>

app/views/stories/_unread_stories.html.erb
<% stories.each do |story| %>

  <% if story.status == 'unread' %>
  
    <%= render 'stories/story_card', story: story %>
  
  <% end %>
<% end %>

app/views/stories/edit.html.erb
<div class="row">
  <aside class="col-sm-5" style="margin:0px 0px 25px 0px">
    <div class="card border-<%= @story.card_color %>">
      <div class="card-header">
        <h4 class="card-title"><%= @story.title %></h4>
      </div>
      <div class="card-body">
        <%= render 'stories/form' , story: @story %>
      </div>
      
    </div>
  </aside>
  <div class="col-sm-7">
    <%= render 'stories/stories_navbar' %>
  </div>
</div>

app/views/stories/index.html.erb
<div class="text-center">
  <h1>Storylist</h1>
  <font size='2' color='#999999'>小説、映画、ドラマなど</font>
</div>
<div class="text-center" style="margin:25px 20px 45px 20px">
  <p><%= link_to '新規ストーリーの追加', new_story_path, class: 'btn btn-lg btn-primary btn-sm' %></p>
  <font size='2' color='#999999'>詳細の確認・編集・削除をする際はカードフレームをクリック</font>
  <br>
  <font size='2' color='#999999'>鑑賞した作品は“未鑑賞”をクリックし、“鑑賞済”に表示変換する</font>
</div>

<%= render 'stories/stories_navbar' %>

app/views/stories/new.html.erb
<div class="row">
  <aside class="col-sm-5" style="margin:0px 0px 25px 0px">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">New Story</h4>
      </div>
      <div class="card-body">
        <%= render 'stories/form' , story: @story %>
      </div>
    </div>
  </aside>
  <div class="col-sm-7">
    <%= render 'stories/stories_navbar' %>
  </div>
</div>

app/views/stories/show.html.erb
<div class="row">
  <aside class="col-md-5" style="margin:0px 0px 25px 0px">
    <div class="card border-<%= @story.card_color %>">
      <div class="card-header">
        <h4 class="card-title"><%= @story.title %></h4>
      </div>
      <div class="card-body">
        <% if @story.content != '' %>
          <div style="margin:0px 0px 25px 0px">
            <font size='2' color='#999999'>内容＆関連情報</font>
            <br><%= @story.content %>
          </div>
        <% end %>
        <div style="padding: 5px 0px 5px 0px">
          <div class="text-right">
          <%= link_to '編集', edit_story_path(@story) ,class: 'btn btn-success btn-sm'%>
          <%= link_to '消去', @story, method: :delete, data: { confirm: 'You sure?' } ,class: 'btn btn-danger btn-sm'%>
          </div>
        </div>
      </div>
    </div>
  </aside>
  <div class="col-md-7">
    <%= render 'stories/stories_navbar' %>
  </div>
</div>